// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SaveCounterMetric provides a mock function with given fields: name, value
func (_m *Repository) SaveCounterMetric(name string, value int64) {
	_m.Called(name, value)
}

// SaveGaugeMetric provides a mock function with given fields: name, value
func (_m *Repository) SaveGaugeMetric(name string, value float64) {
	_m.Called(name, value)
}

type NewRepositoryT interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t NewRepositoryT) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
